config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :products
  resources :ecommerce_websites
  resources :search_histories
  resources :users, only: [:create]

  post "/login", to:"auth#login"
  delete "/logout", to: "auth#logout"
  get "/me", to: "users#me"
  post "/signup", to:"users#create"

  # Routing logic: fallback requests for React Router.
  # Leave this here to help deploy your app later!
  get "*path", to: "fallback#index", constraints: ->(req) { !req.xhr? && req.format.html? }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/search_history.rb
class SearchHistory < ApplicationRecord
  belongs_to :user
end

app/controllers/search_histories_controller.rb
class SearchHistoriesController < ApplicationController
  before_action :set_search_history, only: %i[ show edit update destroy ]

  # GET /search_histories or /search_histories.json
  def index
    @search_histories = SearchHistory.all
  end

  # GET /search_histories/1 or /search_histories/1.json
  def show
  end

  # GET /search_histories/new
  def new
    @search_history = SearchHistory.new
  end

  # GET /search_histories/1/edit
  def edit
  end

  # POST /search_histories or /search_histories.json
  def create
    @search_history = SearchHistory.new(search_history_params)

    respond_to do |format|
      if @search_history.save
        format.html { redirect_to search_history_url(@search_history), notice: "Search history was successfully created." }
        format.json { render :show, status: :created, location: @search_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @search_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /search_histories/1 or /search_histories/1.json
  def update
    respond_to do |format|
      if @search_history.update(search_history_params)
        format.html { redirect_to search_history_url(@search_history), notice: "Search history was successfully updated." }
        format.json { render :show, status: :ok, location: @search_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @search_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_histories/1 or /search_histories/1.json
  def destroy
    @search_history.destroy

    respond_to do |format|
      format.html { redirect_to search_histories_url, notice: "Search history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search_history
      @search_history = SearchHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def search_history_params
      params.require(:search_history).permit(:query, :user_id)
    end
end

app/helpers/search_histories_helper.rb
module SearchHistoriesHelper
end

app/views/search_histories/_form.html.erb
<%= form_with(model: search_history) do |form| %>
  <% if search_history.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(search_history.errors.count, "error") %> prohibited this search_history from being saved:</h2>

      <ul>
        <% search_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :query, style: "display: block" %>
    <%= form.text_field :query %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/search_histories/_search_history.html.erb
<div id="<%= dom_id search_history %>">
  <p>
    <strong>Query:</strong>
    <%= search_history.query %>
  </p>

  <p>
    <strong>User:</strong>
    <%= search_history.user_id %>
  </p>

</div>

app/views/search_histories/edit.html.erb
<h1>Editing search history</h1>

<%= render "form", search_history: @search_history %>

<br>

<div>
  <%= link_to "Show this search history", @search_history %> |
  <%= link_to "Back to search histories", search_histories_path %>
</div>

app/views/search_histories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Search histories</h1>

<div id="search_histories">
  <% @search_histories.each do |search_history| %>
    <%= render search_history %>
    <p>
      <%= link_to "Show this search history", search_history %>
    </p>
  <% end %>
</div>

<%= link_to "New search history", new_search_history_path %>

app/views/search_histories/new.html.erb
<h1>New search history</h1>

<%= render "form", search_history: @search_history %>

<br>

<div>
  <%= link_to "Back to search histories", search_histories_path %>
</div>

app/views/search_histories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @search_history %>

<div>
  <%= link_to "Edit this search history", edit_search_history_path(@search_history) %> |
  <%= link_to "Back to search histories", search_histories_path %>

  <%= button_to "Destroy this search history", @search_history, method: :delete %>
</div>