config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :products
  resources :ecommerce_websites
  resources :search_histories
  resources :users, only: [:create]

  post "/login", to:"auth#login"
  delete "/logout", to: "auth#logout"
  get "/me", to: "users#me"
  post "/signup", to:"users#create"

  # Routing logic: fallback requests for React Router.
  # Leave this here to help deploy your app later!
  get "*path", to: "fallback#index", constraints: ->(req) { !req.xhr? && req.format.html? }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :product
  belongs_to :ecommerce_website
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: %i[ show edit update destroy ]

  # GET /ratings or /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1 or /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings or /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to rating_url(@rating), notice: "Rating was successfully created." }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1 or /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to rating_url(@rating), notice: "Rating was successfully updated." }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1 or /ratings/1.json
  def destroy
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to ratings_url, notice: "Rating was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rating_params
      params.require(:rating).permit(:product_id, :ecommerce_website_id, :rating)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_with(model: rating) do |form| %>
  <% if rating.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
        <% rating.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :ecommerce_website_id, style: "display: block" %>
    <%= form.text_field :ecommerce_website_id %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ratings/_rating.html.erb
<div id="<%= dom_id rating %>">
  <p>
    <strong>Product:</strong>
    <%= rating.product_id %>
  </p>

  <p>
    <strong>Ecommerce website:</strong>
    <%= rating.ecommerce_website_id %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= rating.rating %>
  </p>

</div>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render "form", rating: @rating %>

<br>

<div>
  <%= link_to "Show this rating", @rating %> |
  <%= link_to "Back to ratings", ratings_path %>
</div>

app/views/ratings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ratings</h1>

<div id="ratings">
  <% @ratings.each do |rating| %>
    <%= render rating %>
    <p>
      <%= link_to "Show this rating", rating %>
    </p>
  <% end %>
</div>

<%= link_to "New rating", new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render "form", rating: @rating %>

<br>

<div>
  <%= link_to "Back to ratings", ratings_path %>
</div>

app/views/ratings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rating %>

<div>
  <%= link_to "Edit this rating", edit_rating_path(@rating) %> |
  <%= link_to "Back to ratings", ratings_path %>

  <%= button_to "Destroy this rating", @rating, method: :delete %>
</div>